openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'Amazon Simple Workflow Service #X Amz Target=SimpleWorkflowService.CountClosedWorkflowExecutions #X Amz Target=SimpleWorkflowService.CountClosedWorkflowExecutions #X Amz Target=SimpleWorkflowService.PollForActivityTask #X Amz Target=SimpleWorkflowService.PollForActivityTask API'
  description: <fullname>Amazon Simple Workflow Service</fullname> <p>The Amazon Simple Workflow Service (Amazon SWF) makes it easy to build applications that use Amazon's cloud to coordinate work across distributed components. In Amazon SWF, a <i>task</i> represents a logical unit of work that is performed by a component of your workflow. Coordinating tasks in a workflow involves managing intertask dependencies, scheduling, and concurrency in accordance with the logical flow of the application.</p> <p>Amazon SWF gives you full control over implementing tasks and coordinating them without worrying about underlying complexities such as tracking their progress and maintaining their state.</p> <p>This documentation serves as reference only. For a broader overview of the Amazon SWF programming model, see the <i> <a href="https://docs.aws.amazon.com/amazonswf/latest/developerguide/">Amazon SWF Developer Guide</a> </i>.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: swf
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/swf-2012-01-25.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://swf.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon SWF multi-region endpoint
- url: https://swf.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon SWF multi-region endpoint
- url: http://swf.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon SWF endpoint for China (Beijing) and China (Ningxia)
- url: https://swf.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon SWF endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=SimpleWorkflowService.PollForActivityTask'
paths:
  /#X-Amz-Target=SimpleWorkflowService.PollForActivityTask:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PollForActivityTask
      description: <p>Used by workers to get an <a>ActivityTask</a> from the specified activity <code>taskList</code>. This initiates a long poll, where the service holds the HTTP connection open and responds as soon as a task becomes available. The maximum time the service holds on to the request before responding is 60 seconds. If no task is available within 60 seconds, the poll returns an empty result. An empty result, in this context, means that an ActivityTask is returned, but that the value of taskToken is an empty string. If a task is returned, the worker should use its type to identify and process it correctly.</p> <important> <p>Workers should set their client side socket timeout to at least 70 seconds (10 seconds higher than the maximum time service may hold the poll request).</p> </important> <p> <b>Access Control</b> </p> <p>You can use IAM policies to control this action's access to Amazon SWF resources as follows:</p> <ul> <li> <p>Use a <code>Resource</code> element with the domain name to limit the action to only specified domains.</p> </li> <li> <p>Use an <code>Action</code> element to allow or deny permission to call this action.</p> </li> <li> <p>Constrain the <code>taskList.name</code> parameter by using a <code>Condition</code> element with the <code>swf:taskList.name</code> key to allow the action to access only certain task lists.</p> </li> </ul> <p>If the caller doesn't have sufficient permissions to invoke the action, or the parameter values fall outside the specified constraints, the action fails. The associated event attribute's <code>cause</code> parameter is set to <code>OPERATION_NOT_PERMITTED</code>. For details and example IAM policies, see <a href="https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html">Using IAM to Manage Access to Amazon SWF Workflows</a> in the <i>Amazon SWF Developer Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityTask'
        '480':
          description: UnknownResourceFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownResourceFault'
        '481':
          description: OperationNotPermittedFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationNotPermittedFault'
        '482':
          description: LimitExceededFault
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitExceededFault'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PollForActivityTaskInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - SimpleWorkflowService.PollForActivityTask
        example: SimpleWorkflowService.PollForActivityTask
      summary: Amazon SWF Poll for Activity Task
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=SimpleWorkflowService.PollForActivityTask'
components:
  schemas:
    OperationNotPermittedFault: {}
    DomainName:
      type: string
      minLength: 1
      maxLength: 256
    TaskToken:
      type: string
      minLength: 1
      maxLength: 1024
    ActivityType:
      type: object
      required:
      - name
      - version
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: <p>The name of this activity.</p> <note> <p>The combination of activity type name and version must be unique within a domain.</p> </note>
        version:
          allOf:
          - $ref: '#/components/schemas/Version'
          - description: <p>The version of this activity.</p> <note> <p>The combination of activity type name and version must be unique with in a domain.</p> </note>
      description: Represents an activity type.
    UnknownResourceFault: {}
    WorkflowExecution:
      type: object
      required:
      - workflowId
      - runId
      properties:
        workflowId:
          allOf:
          - $ref: '#/components/schemas/WorkflowId'
          - description: The user defined identifier associated with the workflow execution.
        runId:
          allOf:
          - $ref: '#/components/schemas/WorkflowRunId'
          - description: A system-generated unique identifier for the workflow execution.
      description: Represents a workflow execution.
    PollForActivityTaskInput:
      type: object
      required:
      - domain
      - taskList
      title: PollForActivityTaskInput
      properties:
        domain:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: The name of the domain that contains the task lists being polled.
        taskList:
          allOf:
          - $ref: '#/components/schemas/TaskList'
          - description: <p>Specifies the task list to poll for activity tasks.</p> <p>The specified string must not start or end with whitespace. It must not contain a <code>:</code> (colon), <code>/</code> (slash), <code>|</code> (vertical bar), or any control characters (<code>\u0000-\u001f</code> | <code>\u007f-\u009f</code>). Also, it must <i>not</i> be the literal string <code>arn</code>.</p>
        identity:
          allOf:
          - $ref: '#/components/schemas/Identity'
          - description: Identity of the worker making the request, recorded in the <code>ActivityTaskStarted</code> event in the workflow history. This enables diagnostic tracing when problems arise. The form of this identity is user defined.
    WorkflowId:
      type: string
      minLength: 1
      maxLength: 256
    ActivityId:
      type: string
      minLength: 1
      maxLength: 256
    Identity:
      type: string
      maxLength: 256
    LimitExceededFault: {}
    ActivityTask:
      type: object
      required:
      - taskToken
      - activityId
      - startedEventId
      - workflowExecution
      - activityType
      properties:
        taskToken:
          allOf:
          - $ref: '#/components/schemas/TaskToken'
          - description: The opaque string used as a handle on the task. This token is used by workers to communicate progress and response information back to the system about the task.
        activityId:
          allOf:
          - $ref: '#/components/schemas/ActivityId'
          - description: The unique ID of the task.
        startedEventId:
          allOf:
          - $ref: '#/components/schemas/EventId'
          - description: The ID of the <code>ActivityTaskStarted</code> event recorded in the history.
        workflowExecution:
          allOf:
          - $ref: '#/components/schemas/WorkflowExecution'
          - description: The workflow execution that started this activity task.
        activityType:
          allOf:
          - $ref: '#/components/schemas/ActivityType'
          - description: The type of this activity task.
        input:
          allOf:
          - $ref: '#/components/schemas/Data'
          - description: The inputs provided when the activity task was scheduled. The form of the input is user defined and should be meaningful to the activity implementation.
      description: Unit of work sent to an activity worker.
    Name:
      type: string
      minLength: 1
      maxLength: 256
    WorkflowRunId:
      type: string
      minLength: 1
      maxLength: 64
    Data:
      type: string
      maxLength: 32768
    EventId:
      type: integer
    TaskList:
      type: object
      required:
      - name
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the task list.
      description: Represents a task list.
    Version:
      type: string
      minLength: 1
      maxLength: 64
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/swf/
x-hasEquivalentPaths: true
